### ISSUE TITLE
Enable GitHub Actions for Continuous Integration

### ISSUE THREAD

**Issue by szabgab** [drclaw1394/perl-io-fd#1]
As mentioned in the Perl Weekly https://perlweekly.com/ as well, having a Continuous Integration (CI) system for a project can reduce the feedback loop and allow the developer(s) and the contributor(s) to progress in a faster and safer way. Without the fear of releasing a broken version and finding out about it only days later when the CPAN Testers get around to testing and reporting it.

In particular I am trying to help each CPAN author by configuring GitHub Actions for them and sometimes by writing tests for them.

For a few previous PRs see the articles and videos here: https://perlmaven.com/os
For more information about CI check the articles here: https://perlmaven.com/ci

Would you be interested in a Pull-Request configuring GitHub Actions for this repo?

**Comment by drclaw1394** [comment]
Sorry of the delayed reply. I've been away for a couple weeks.
Yes I am interested in your suggested GitHub Actions pull request. Fire away!

**Comment by szabgab** [comment]
Sure. Now I see that a minimum of Perl 5.36 is required in the Makefile.PL. Does this module really use features only available in  perl 5.36?

**Comment by drclaw1394** [comment]
I think the some of the XS macros and perlapi I've been using are fairly new (?), or I have some other configuration problem.  I would like to expand to older perl's but I need more XS knowledge...

**Comment by szabgab** [comment]
I created a branch in which removed the minimum version and configured GitHub Actions to run on older versions of perl as well.
Everything fails, but this could be the way for you to see what's going on. See the results here: https://github.com/szabgab/perl-io-fd/actions/runs/3470512902

**Comment by drclaw1394** [comment]
Thanks will have a look when I get the chance.
